name: ndfl
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.0.0
  provider: ^6.0.5
  crop_image: ^1.0.16
  screenshot: ^3.0.0
  colorfilter_generator: ^0.0.8
  blur: ^3.1.0
  pixel_color_picker: ^1.0.0
  flutter_colorpicker: ^1.1.0
  lindi_sticker_widget: ^0.0.4
  text_editor: ^0.7.0
  painter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
    - family: AlexBrush
      fonts:
        - asset: assets/fonts/AlexBrush-Regular.ttf
    - family: Allura
      fonts:
        - asset: assets/fonts/Allura-Regular.otf
    - family: Arizonia
      fonts:
        - asset: assets/fonts/Arizonia-Regular.ttf
    - family: ChunkFive
      fonts:
        - asset: assets/fonts/ChunkFive-Regular.otf
    - family: GrandHotel
      fonts:
        - asset: assets/fonts/GrandHotel-Regular.otf
    - family: GreatVibes
      fonts:
        - asset: assets/fonts/GreatVibes-Regular.otf
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster_1.3.otf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: OstrichSans
      fonts:
        - asset: assets/fonts/OstrichSans-Medium.otf
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico.ttf
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.otf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: SEASRN
      fonts:
        - asset: assets/fonts/SEASRN.ttf
    - family: Windsong
      fonts:
        - asset: assets/fonts/Windsong.ttf