name: ndfl
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.0.0
  provider: ^6.0.5
  crop_image: ^1.0.16
  screenshot: ^3.0.0
  colorfilter_generator: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
